name: typespeed
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  confetti: ^0.8.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  hugeicons: ^1.1.4
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
